-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQglkFs/G/gvL7Uyp9+
cbTgxgpi0EWb2CCB/A/YMvCx7/WgCgYIKoZIzj0DAQehRANCAASpK5ATBNbBc7TT
mCkcQ/jALIQGfgOKrkPjvicRbrCt8F03G6T/rLdQ+6KVBU/d/1y3VmyA8kHqs6l6
vSHQG2ft
-----END PRIVATE KEY-----